// Writes shared/version.ts from package.json so the User-Agent carries the
// published version without reading files at runtime (banned by n8n verification).
import { readFileSync, writeFileSync } from 'node:fs';

const { version } = JSON.parse(readFileSync(new URL('../package.json', import.meta.url), 'utf8'));
const target = new URL('../shared/version.ts', import.meta.url);
const content = `// Generated by scripts/sync-version.mjs. Do not edit.\nexport const PACKAGE_VERSION = '${version}';\n`;

let current = '';
try {
	current = readFileSync(target, 'utf8');
} catch {
	// First run: file doesn't exist yet.
}
if (current !== content) writeFileSync(target, content);
